### ISSUE TITLE
Is this compatible with MultiMC?

### ISSUE THREAD

**Issue by Immortalin** [chadmiller/minecraft-linux-support#3]
Is this compatible with [MultiMC](https://multimc.org/)?

**Comment by chadmiller** [comment]
I doubt it is. The startup program we provide is important to hooking to the new security profile. I doubt MultiMC uses it.

**Comment by mk-pmb** [comment]
Hi! Thank you for your attempt to help me run MC securely, especially [with MultiMC](https://github.com/MultiMC/MultiMC5/issues/1519). Fortunately I was wise enough to read the shell scripts that their deb package installs. My initial urge was to help them fix it, but I can't find an easy communication channel so I think the AppArmor approach is more sustainable. I'll try and make sense of what's already here, then try and discover what's still to be done. I just wanted to express my gratitude now while the feeling is fresh. :-)
